version: '3'

services:

  flask:
    build:
      context: ./flask
    ports:
      - 5000:5000 # host : container
    env_file:
      - ./misc/credentials.env
    depends_on:
      - mongo
    container_name: flask
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - 27017:27017
    volumes:
     - ./mongodb/database:/data/db
    container_name: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    container_name: mongo-express
  nginx:
    image: nginx
    volumes:
     - ./nginx:/app
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
    depends_on:
      - flask
    container_name: nginx
  
